# Generated by Django 2.1.5 on 2019-01-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskMum', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='桌号')),
            ],
            options={
                'verbose_name_plural': '桌号',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='采购', max_length=50, verbose_name='备注')),
                ('Time', models.DateTimeField(verbose_name='时间')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
            ],
            options={
                'verbose_name_plural': '支出',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='菜名')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('Img', models.ImageField(upload_to='img', verbose_name='照片')),
                ('Introduction', models.CharField(max_length=50, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='菜品分类')),
                ('Sort', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '菜品分类',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False, verbose_name='订单号')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('Off', models.CharField(choices=[('1', '原价'), ('0.98', '98折'), ('0.88', '88折')], default=1.0, max_length=6, verbose_name='折扣')),
                ('PayTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('OrderState', models.CharField(choices=[('0', '未付款'), ('1', '微信'), ('2', '支付宝'), ('3', '现金')], default='未付款', max_length=6, verbose_name='付款状态')),
                ('CookState', models.CharField(choices=[('1', '已做'), ('0', '未做')], default='未做', max_length=6, verbose_name='后厨状态')),
                ('Comments', models.CharField(default='无', max_length=200, verbose_name='备注')),
                ('Desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Desk', verbose_name='桌号')),
            ],
            options={
                'verbose_name_plural': '订单',
                'ordering': ['Time'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=1, verbose_name='数量')),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='价格')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Order')),
            ],
            options={
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('OpenId', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户d')),
                ('Name', models.CharField(max_length=50, verbose_name='昵称')),
                ('Session', models.CharField(max_length=50, verbose_name='session')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='Menus',
            field=models.ManyToManyField(through='Data.OrderDetail', to='Data.Menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.MenuType', verbose_name='菜品分类'),
        ),
    ]
