# Generated by Django 2.1.5 on 2019-01-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='id',
        ),
        migrations.AlterField(
            model_name='desk',
            name='DeskMum',
            field=models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False, verbose_name='桌号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='OpenId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
