# Generated by Django 2.1.5 on 2019-01-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20190120_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Data.Desk', verbose_name='桌号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Data.User', verbose_name='用户'),
        ),
    ]
