# Generated by Django 2.1.5 on 2019-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20190127_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='Menus',
            field=models.ManyToManyField(to='Data.Menu'),
        ),
    ]
