# Generated by Django 2.1.7 on 2019-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20190213_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CookState',
            field=models.CharField(choices=[('1', '已做'), ('0', '未做')], default='0', max_length=6, verbose_name='后厨状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Off',
            field=models.CharField(choices=[('1', '原价'), ('0.98', '98折'), ('0.88', '88折')], default='1', max_length=6, verbose_name='折扣'),
        ),
    ]
