# Generated by Django 2.1.7 on 2019-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_auto_20190301_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MRP',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='积分'),
        ),
    ]
